"""first

Revision ID: 214d061f1647
Revises: 
Create Date: 2024-08-15 13:26:46.893268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214d061f1647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('users')
    op.drop_table('luggages')
    op.drop_table('activities')
    op.drop_table('vacations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('trip_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='fk_vacations_activity_id_activities'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_vacations_trip_id_trips'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_vacations_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.INTEGER(), nullable=False),
    sa.Column('adv_scale', sa.INTEGER(), nullable=False),
    sa.Column('is_alone', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('desc', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('luggages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('style_shirt', sa.BOOLEAN(), nullable=False),
    sa.Column('style_pants', sa.BOOLEAN(), nullable=False),
    sa.Column('style_accessories', sa.BOOLEAN(), nullable=False),
    sa.Column('is_summer', sa.BOOLEAN(), nullable=False),
    sa.Column('pants', sa.INTEGER(), nullable=False),
    sa.Column('shirts', sa.INTEGER(), nullable=False),
    sa.Column('other_clothes', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_luggages_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=False),
    sa.Column('is_alone', sa.BOOLEAN(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('season', sa.VARCHAR(), nullable=False),
    sa.Column('is_winter', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('is_flying', sa.BOOLEAN(), nullable=True),
    sa.Column('weight_limit', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
